const translations = {
  "en-US": {
    header: { badge: "HACKATHON MVP", status: "Murf Falcon · Live", demoBanner: "Demo mode active - sit back and watch", switchThemeTo: "Switch to" },
    hero: { eyebrow: "VOICE-FIRST INTERACTION", title1: "Navigate the web with your", titleAccent: "voice", subtitle: "SpeakSite turns a standard demo website into a voice-first enterprise experience with real-time command parsing, responsive UI feedback, and spoken confirmations.", trySaying: "TRY SAYING", cmd1: '"go to signup page"', cmd2: '"fill email with me@gmail.com"', cmd3: '"submit form"' },
    nav: { home: "Home", signup: "Sign Up", contact: "Contact" },
    homePage: { tag: "ENTERPRISE PLATFORM", title: "Work smarter, not harder.", subtitle: "Build trust in voice-first workflows with a polished SaaS-style experience that makes navigation, form entry, and spoken confirmations feel product-ready.", ctaPrimary: "Get started free ->", ctaPrimaryLoading: "Opening...", ctaSecondary: "Watch demo", ctaSecondaryRunning: "Demo running...", demoWarmup: "Demo mode is still warming up. Try again in a moment.", stat1Value: "48K+", stat1Label: "Active teams", stat2Value: "99.9%", stat2Label: "Uptime SLA", stat3Value: "4.9★", stat3Label: "User rating", feature1Title: "Fast by default", feature1Desc: "Sub-100ms response times globally with edge infrastructure.", feature2Title: "Enterprise security", feature2Desc: "SOC 2 Type II certified with end-to-end encryption.", feature3Title: "Real-time analytics", feature3Desc: "Live dashboards with custom KPIs and export options.", feature4Title: "Team collaboration", feature4Desc: "Comments, mentions, and shared workspaces built in." },
    signupPage: { tag: "CREATE ACCOUNT", title: "Join thousands of teams", subtitle: "Set up your free account in under 2 minutes. No credit card required.", labelFirstName: "First Name", labelLastName: "Last Name", labelEmail: "Email Address", labelPassword: "Password", placeholderFirstName: "Rahul", placeholderLastName: "Sharma", placeholderEmail: "rahul@company.com", placeholderPassword: "Min. 8 characters", voiceBadge: "voice", hint: 'Say "submit form" or click ->', submitBtn: "Create account", successMsg: "Account created successfully! Welcome aboard.", successIcon: "OK", subtitleAlt: "Set up your workspace in minutes and manage the form using voice or manual entry." },
    contactPage: { tag: "GET IN TOUCH", title: "We'd love to hear from you", subtitle: "Send us a message and our team will respond within one business day.", labelName: "Your Name", labelEmail: "Email", labelMessage: "Message", placeholderName: "Full name", placeholderEmail: "you@company.com", placeholderMsg: "Tell us how we can help...", voiceBadge: "voice", hint: 'Say "submit form" or click ->', submitBtn: "Send message", successMsg: "Message sent! We'll be in touch within 24 hours.", successIcon: "OK" },
    voicePanel: { title: "VOICE CONTROL", transcript: "TRANSCRIPT", actionLog: "ACTION LOG", response: "RESPONSE", waiting: "Waiting for voice input...", clickToStart: "Click to start listening", listening: "Listening... speak now", processing: "Processing command...", speaking: "Playing response...", noCommands: "No commands yet", tryChips: "Try the chips below", chip1: "signup page", chip2: "contact page", chip3: "fill name", chip4: "submit", idlePrompt: "Click mic and say a command", repeatReady: "I am ready for your next command.", notCaught: "I didn't catch that. Try again.", unsupported: "Your browser doesn't support voice input. Try Chrome or Edge.", demoRunning: "Demo running...", noSpeech: "No speech detected.", noMatch: "I couldn't match that to a command." },
    status: { idle: "Ready", listening: "Listening...", processing: "Processing...", speaking: "Speaking..." },
    languageSelector: { chooseLanguage: "Choose Language", female: "Female", male: "Male" },
    onboarding: { step1Title: "Welcome to SpeakSite", step1Sub: "The web, navigated entirely by voice.", poweredBy: "POWERED BY MURF FALCON AI", step2Title: "Here's what you can say", card1Label: "NAVIGATE", card1Cmd: '"go to signup page"', card2Label: "FILL FORMS", card2Cmd: '"fill email with you@mail.com"', card3Label: "SUBMIT", card3Cmd: '"submit form"', step3Title: "Choose your language", step3Sub: "SpeakSite speaks your language, powered by Murf Falcon.", startBtn: "Start using SpeakSite", skipLink: "Skip intro" },
    helpModal: { title: "Voice Commands", subtitle: "Say any of these to control SpeakSite", navSection: "NAVIGATION", formSection: "FORM FILLING", langSection: "LANGUAGE", demoSection: "DEMO", themeSection: "THEME", cmd_home: "go to home page", cmd_signup: "go to signup page", cmd_contact: "open contact page", cmd_fillName: "fill name with [value]", cmd_fillEmail: "fill email with [value]", cmd_fillMsg: "fill message with [value]", cmd_submit: "submit form", cmd_hindi: "switch to hindi", cmd_english: "switch to english", cmd_demo: "start demo", cmd_stopDemo: "stop demo", cmd_help: "help", cmd_light: "switch to light mode", cmd_dark: "switch to dark mode", desc_home: "Opens home", desc_signup: "Opens sign up", desc_contact: "Opens contact", desc_fillName: "Fills name field", desc_fillEmail: "Fills email field", desc_fillMsg: "Fills message field", desc_submit: "Submits current form", desc_hindi: "Changes to Hindi", desc_english: "Changes to English", desc_demo: "Runs guided demo", desc_stopDemo: "Stops demo", desc_help: "Shows this panel", desc_light: "Switches to light theme", desc_dark: "Switches to dark theme", closeBtn: "x" },
    guidedDemo: { runBtn: "Run Demo", runIcon: "RUN", demoMode: "DEMO MODE", step: "Step", stepOf: "of", skipStep: "Skip step", stopDemo: "Stop demo", running: "Demo running...", label1: "Introduction", label2: "Navigating to Sign Up", label3: "Filling name field", label4: "Filling email field", label5: "Submitting form", label6: "Demo complete" },
    theme: { dark: "Dark", light: "Light" },
    logs: { navigatedHome: "Navigated to Home", navigatedSignup: "Navigated to Sign Up", navigatedContact: "Navigated to Contact", filledField: "Filled", submittedForm: "Submitted", submittedSuffix: "form", repeatedResponse: "Repeated last response", langSwitched: "Language switched to", helpOpened: "Opened help panel", helpClosed: "Closed help panel", unrecognized: "Unrecognized command", themeLight: "Theme -> Light mode", themeDark: "Theme -> Dark mode", demoStopped: "Demo stopped by user", demoStartedButton: "Demo started via Watch Demo button", getStartedNav: "Navigated to Sign Up via Get Started" }
  },
  "hi-IN": {
    header: { badge: "हैकाथॉन MVP", status: "Murf Falcon · लाइव", demoBanner: "डेमो मोड सक्रिय है - आराम से देखें", switchThemeTo: "बदलें" },
    hero: { eyebrow: "वॉयस-फर्स्ट इंटरैक्शन", title1: "अपनी", titleAccent: "आवाज़", subtitle: "SpeakSite एक सामान्य डेमो वेबसाइट को वॉयस-फर्स्ट अनुभव में बदलता है — रियल-टाइम कमांड पार्सिंग और बोली गई पुष्टि के साथ।", trySaying: "यह कहकर देखें", cmd1: '"साइनअप पेज पर जाओ"', cmd2: '"ईमेल भरो me@gmail.com से"', cmd3: '"फॉर्म सबमिट करो"' },
    nav: { home: "होम", signup: "साइन अप", contact: "संपर्क" },
    homePage: { tag: "एंटरप्राइज़ प्लेटफ़ॉर्म", title: "स्मार्ट तरीके से काम करें।", subtitle: "वॉयस-फर्स्ट वर्कफ़्लो के साथ एक पॉलिश्ड SaaS अनुभव बनाएं।", ctaPrimary: "मुफ़्त शुरू करें ->", ctaPrimaryLoading: "खोला जा रहा है...", ctaSecondary: "डेमो देखें", ctaSecondaryRunning: "डेमो चल रहा है...", demoWarmup: "डेमो मोड अभी तैयार हो रहा है। थोड़ी देर बाद फिर प्रयास करें।", stat1Value: "48K+", stat1Label: "सक्रिय टीमें", stat2Value: "99.9%", stat2Label: "अपटाइम SLA", stat3Value: "4.9★", stat3Label: "यूज़र रेटिंग", feature1Title: "डिफ़ॉल्ट रूप से तेज़", feature1Desc: "एज इंफ्रास्ट्रक्चर के साथ 100ms से कम रिस्पॉन्स टाइम।", feature2Title: "एंटरप्राइज़ सुरक्षा", feature2Desc: "SOC 2 Type II प्रमाणित एंड-टू-एंड एन्क्रिप्शन।", feature3Title: "रियल-टाइम एनालिटिक्स", feature3Desc: "कस्टम KPI के साथ लाइव डैशबोर्ड।", feature4Title: "टीम सहयोग", feature4Desc: "कमेंट्स, मेंशन और शेयर्ड वर्कस्पेस।" },
    signupPage: { tag: "खाता बनाएं", title: "हज़ारों टीमों से जुड़ें", subtitle: "2 मिनट से कम में अपना मुफ़्त खाता सेट करें।", labelFirstName: "पहला नाम", labelLastName: "अंतिम नाम", labelEmail: "ईमेल पता", labelPassword: "पासवर्ड", placeholderFirstName: "राहुल", placeholderLastName: "शर्मा", placeholderEmail: "rahul@company.com", placeholderPassword: "न्यूनतम 8 अक्षर", voiceBadge: "वॉयस", hint: '"फॉर्म सबमिट करो" कहें या क्लिक करें ->', submitBtn: "खाता बनाएं", successMsg: "खाता सफलतापूर्वक बनाया गया! स्वागत है।", successIcon: "ठीक", subtitleAlt: "कुछ मिनटों में अपना वर्कस्पेस सेट करें और फॉर्म को वॉयस या मैनुअल एंट्री से भरें।" },
    contactPage: { tag: "संपर्क करें", title: "हम आपसे सुनना चाहते हैं", subtitle: "हमें एक संदेश भेजें और हमारी टीम एक कार्य दिवस के भीतर जवाब देगी।", labelName: "आपका नाम", labelEmail: "ईमेल", labelMessage: "संदेश", placeholderName: "पूरा नाम", placeholderEmail: "you@company.com", placeholderMsg: "बताएं हम कैसे मदद कर सकते हैं...", voiceBadge: "वॉयस", hint: '"फॉर्म सबमिट करो" कहें या क्लिक करें ->', submitBtn: "संदेश भेजें", successMsg: "संदेश भेजा गया! हम 24 घंटे में संपर्क करेंगे।", successIcon: "ठीक" },
    voicePanel: { title: "वॉयस कंट्रोल", transcript: "ट्रांसक्रिप्ट", actionLog: "एक्शन लॉग", response: "जवाब", waiting: "वॉयस इनपुट का इंतज़ार है...", clickToStart: "सुनना शुरू करने के लिए क्लिक करें", listening: "सुन रहा हूँ... अभी बोलें", processing: "कमांड प्रोसेस हो रही है...", speaking: "जवाब चल रहा है...", noCommands: "अभी कोई कमांड नहीं", tryChips: "नीचे दिए चिप्स आज़माएं", chip1: "साइनअप पेज", chip2: "संपर्क पेज", chip3: "नाम भरो", chip4: "सबमिट", idlePrompt: "माइक क्लिक करें और कमांड बोलें", repeatReady: "मैं आपके अगले कमांड के लिए तैयार हूँ।", notCaught: "मैं समझ नहीं पाया। फिर से कोशिश करें।", unsupported: "आपका ब्राउज़र वॉयस इनपुट सपोर्ट नहीं करता। Chrome या Edge आज़माएं।", demoRunning: "डेमो चल रहा है...", noSpeech: "कोई आवाज़ नहीं मिली।", noMatch: "इसे कमांड से मिलाया नहीं जा सका।" },
    status: { idle: "तैयार", listening: "सुन रहा हूँ...", processing: "प्रोसेसिंग...", speaking: "बोल रहा हूँ..." },
    languageSelector: { chooseLanguage: "भाषा चुनें", female: "महिला", male: "पुरुष" },
    onboarding: { step1Title: "SpeakSite में आपका स्वागत है", step1Sub: "वेब, पूरी तरह आवाज़ से नेविगेट किया गया।", poweredBy: "MURF FALCON AI द्वारा संचालित", step2Title: "आप यह कह सकते हैं", card1Label: "नेविगेट", card1Cmd: '"साइनअप पेज पर जाओ"', card2Label: "फॉर्म भरें", card2Cmd: '"ईमेल भरो"', card3Label: "सबमिट", card3Cmd: '"फॉर्म सबमिट करो"', step3Title: "अपनी भाषा चुनें", step3Sub: "SpeakSite आपकी भाषा में बोलता है, Murf Falcon से।", startBtn: "SpeakSite शुरू करें", skipLink: "परिचय छोड़ें" },
    helpModal: { title: "वॉयस कमांड", subtitle: "SpeakSite को कंट्रोल करने के लिए ये कहें", navSection: "नेविगेशन", formSection: "फॉर्म भरना", langSection: "भाषा", demoSection: "डेमो", themeSection: "थीम", cmd_home: "होम पेज पर जाओ", cmd_signup: "साइनअप पेज पर जाओ", cmd_contact: "संपर्क पेज खोलो", cmd_fillName: "नाम भरो [मान] से", cmd_fillEmail: "ईमेल भरो [मान] से", cmd_fillMsg: "संदेश भरो [मान] से", cmd_submit: "फॉर्म सबमिट करो", cmd_hindi: "हिंदी पर स्विच करो", cmd_english: "अंग्रेज़ी पर स्विच करो", cmd_demo: "डेमो शुरू करो", cmd_stopDemo: "डेमो बंद करो", cmd_help: "सहायता", cmd_light: "लाइट मोड पर स्विच करो", cmd_dark: "डार्क मोड पर स्विच करो", desc_home: "होम खोलता है", desc_signup: "साइन अप खोलता है", desc_contact: "संपर्क खोलता है", desc_fillName: "नाम फ़ील्ड भरता है", desc_fillEmail: "ईमेल फ़ील्ड भरता है", desc_fillMsg: "संदेश फ़ील्ड भरता है", desc_submit: "वर्तमान फॉर्म सबमिट करता है", desc_hindi: "हिंदी में बदलता है", desc_english: "अंग्रेज़ी में बदलता है", desc_demo: "गाइडेड डेमो चलाता है", desc_stopDemo: "डेमो रोकता है", desc_help: "यह पैनल दिखाता है", desc_light: "लाइट थीम पर स्विच करता है", desc_dark: "डार्क थीम पर स्विच करता है", closeBtn: "x" },
    guidedDemo: { runBtn: "डेमो चलाएं", runIcon: "RUN", demoMode: "डेमो मोड", step: "चरण", stepOf: "में से", skipStep: "चरण छोड़ें", stopDemo: "डेमो बंद करें", running: "डेमो चल रहा है...", label1: "परिचय", label2: "साइन अप पर जाना", label3: "नाम फ़ील्ड भरना", label4: "ईमेल फ़ील्ड भरना", label5: "फॉर्म सबमिट करना", label6: "डेमो पूरा हुआ" },
    theme: { dark: "डार्क", light: "लाइट" },
    logs: { navigatedHome: "होम पर गए", navigatedSignup: "साइन अप पर गए", navigatedContact: "संपर्क पर गए", filledField: "भरा", submittedForm: "सबमिट किया", submittedSuffix: "फॉर्म", repeatedResponse: "पिछला जवाब दोहराया", langSwitched: "भाषा बदली", helpOpened: "सहायता पैनल खोला", helpClosed: "सहायता पैनल बंद किया", unrecognized: "कमांड समझ नहीं आई", themeLight: "थीम -> लाइट मोड", themeDark: "थीम -> डार्क मोड", demoStopped: "डेमो उपयोगकर्ता द्वारा रोका गया", demoStartedButton: "वॉच डेमो बटन से डेमो शुरू हुआ", getStartedNav: "गेट स्टार्टेड से साइन अप पर गए" }
  },
  "es-ES": {
    header: { badge: "MVP HACKATHON", status: "Murf Falcon · En vivo", demoBanner: "Modo demo activo - solo mira", switchThemeTo: "Cambiar a" },
    hero: { eyebrow: "INTERACCION POR VOZ", title1: "Navega la web con tu", titleAccent: "voz", subtitle: "SpeakSite convierte una web de demostracion en una experiencia empresarial centrada en voz con comandos en tiempo real y confirmaciones habladas.", trySaying: "INTENTA DECIR", cmd1: '"ir a pagina de registro"', cmd2: '"llenar correo con me@gmail.com"', cmd3: '"enviar formulario"' },
    nav: { home: "Inicio", signup: "Registro", contact: "Contacto" },
    homePage: { tag: "PLATAFORMA EMPRESARIAL", title: "Trabaja de forma mas inteligente.", subtitle: "Crea confianza en flujos de trabajo por voz con una experiencia SaaS pulida.", ctaPrimary: "Empezar gratis ->", ctaPrimaryLoading: "Abriendo...", ctaSecondary: "Ver demo", ctaSecondaryRunning: "Demo en ejecucion...", demoWarmup: "El modo demo aun se esta preparando. Intentalo de nuevo en un momento.", stat1Value: "48K+", stat1Label: "Equipos activos", stat2Value: "99.9%", stat2Label: "SLA de actividad", stat3Value: "4.9★", stat3Label: "Valoracion", feature1Title: "Rapido por defecto", feature1Desc: "Tiempos de respuesta inferiores a 100 ms con infraestructura edge.", feature2Title: "Seguridad empresarial", feature2Desc: "Certificacion SOC 2 Tipo II con cifrado de extremo a extremo.", feature3Title: "Analitica en tiempo real", feature3Desc: "Paneles en vivo con KPIs personalizados y opciones de exportacion.", feature4Title: "Colaboracion en equipo", feature4Desc: "Comentarios, menciones y espacios compartidos integrados." },
    signupPage: { tag: "CREAR CUENTA", title: "Unete a miles de equipos", subtitle: "Configura tu cuenta gratuita en menos de 2 minutos.", labelFirstName: "Nombre", labelLastName: "Apellido", labelEmail: "Correo electronico", labelPassword: "Contrasena", placeholderFirstName: "Carlos", placeholderLastName: "Garcia", placeholderEmail: "carlos@empresa.com", placeholderPassword: "Min. 8 caracteres", voiceBadge: "voz", hint: 'Di "enviar formulario" o haz clic ->', submitBtn: "Crear cuenta", successMsg: "Cuenta creada con exito. Bienvenido.", successIcon: "OK", subtitleAlt: "Configura tu espacio de trabajo en minutos y gestiona el formulario con voz o entrada manual." },
    contactPage: { tag: "CONTACTANOS", title: "Nos encantaria saber de ti", subtitle: "Envianos un mensaje y nuestro equipo respondera en un dia habil.", labelName: "Tu nombre", labelEmail: "Correo", labelMessage: "Mensaje", placeholderName: "Nombre completo", placeholderEmail: "tu@empresa.com", placeholderMsg: "Cuentanos como podemos ayudarte...", voiceBadge: "voz", hint: 'Di "enviar formulario" o haz clic ->', submitBtn: "Enviar mensaje", successMsg: "Mensaje enviado. Te responderemos en 24 horas.", successIcon: "OK" },
    voicePanel: { title: "CONTROL DE VOZ", transcript: "TRANSCRIPCION", actionLog: "REGISTRO DE ACCIONES", response: "RESPUESTA", waiting: "Esperando entrada de voz...", clickToStart: "Haz clic para comenzar", listening: "Escuchando... habla ahora", processing: "Procesando comando...", speaking: "Reproduciendo respuesta...", noCommands: "Sin comandos aun", tryChips: "Prueba los chips de abajo", chip1: "pagina de registro", chip2: "pagina de contacto", chip3: "llenar nombre", chip4: "enviar", idlePrompt: "Haz clic en el microfono y di un comando", repeatReady: "Estoy listo para tu siguiente comando.", notCaught: "No entendi eso. Intentalo de nuevo.", unsupported: "Tu navegador no soporta entrada de voz. Prueba Chrome o Edge.", demoRunning: "Demo en ejecucion...", noSpeech: "No se detecto voz.", noMatch: "No pude relacionarlo con un comando." },
    status: { idle: "Listo", listening: "Escuchando...", processing: "Procesando...", speaking: "Hablando..." },
    languageSelector: { chooseLanguage: "Elegir idioma", female: "Femenino", male: "Masculino" },
    onboarding: { step1Title: "Bienvenido a SpeakSite", step1Sub: "La web, navegada completamente por voz.", poweredBy: "IMPULSADO POR MURF FALCON AI", step2Title: "Esto es lo que puedes decir", card1Label: "NAVEGAR", card1Cmd: '"ir a pagina de registro"', card2Label: "LLENAR FORMULARIOS", card2Cmd: '"llenar correo con tu@correo.com"', card3Label: "ENVIAR", card3Cmd: '"enviar formulario"', step3Title: "Elige tu idioma", step3Sub: "SpeakSite habla tu idioma, con Murf Falcon.", startBtn: "Empezar a usar SpeakSite", skipLink: "Omitir introduccion" },
    helpModal: { title: "Comandos de voz", subtitle: "Di cualquiera de estos para controlar SpeakSite", navSection: "NAVEGACION", formSection: "FORMULARIOS", langSection: "IDIOMA", demoSection: "DEMO", themeSection: "TEMA", cmd_home: "ir a pagina de inicio", cmd_signup: "ir a pagina de registro", cmd_contact: "abrir pagina de contacto", cmd_fillName: "llenar nombre con [valor]", cmd_fillEmail: "llenar correo con [valor]", cmd_fillMsg: "llenar mensaje con [valor]", cmd_submit: "enviar formulario", cmd_hindi: "cambiar a hindi", cmd_english: "cambiar a ingles", cmd_demo: "iniciar demo", cmd_stopDemo: "detener demo", cmd_help: "ayuda", cmd_light: "cambiar a modo claro", cmd_dark: "cambiar a modo oscuro", desc_home: "Abre inicio", desc_signup: "Abre registro", desc_contact: "Abre contacto", desc_fillName: "Rellena el campo nombre", desc_fillEmail: "Rellena el campo correo", desc_fillMsg: "Rellena el campo mensaje", desc_submit: "Envia el formulario actual", desc_hindi: "Cambia a hindi", desc_english: "Cambia a ingles", desc_demo: "Ejecuta la demo guiada", desc_stopDemo: "Detiene la demo", desc_help: "Muestra este panel", desc_light: "Cambia al tema claro", desc_dark: "Cambia al tema oscuro", closeBtn: "x" },
    guidedDemo: { runBtn: "Ejecutar demo", runIcon: "RUN", demoMode: "MODO DEMO", step: "Paso", stepOf: "de", skipStep: "Saltar paso", stopDemo: "Detener demo", running: "Demo en ejecucion...", label1: "Introduccion", label2: "Navegando a Registro", label3: "Rellenando nombre", label4: "Rellenando correo", label5: "Enviando formulario", label6: "Demo completada" },
    theme: { dark: "Oscuro", light: "Claro" },
    logs: { navigatedHome: "Navegado a Inicio", navigatedSignup: "Navegado a Registro", navigatedContact: "Navegado a Contacto", filledField: "Rellenado", submittedForm: "Enviado", submittedSuffix: "formulario", repeatedResponse: "Respuesta repetida", langSwitched: "Idioma cambiado a", helpOpened: "Panel de ayuda abierto", helpClosed: "Panel de ayuda cerrado", unrecognized: "Comando no reconocido", themeLight: "Tema -> modo claro", themeDark: "Tema -> modo oscuro", demoStopped: "Demo detenida por el usuario", demoStartedButton: "Demo iniciada desde Ver demo", getStartedNav: "Navegado a Registro desde Empezar gratis" }
  },
  "fr-FR": {
    header: { badge: "MVP HACKATHON", status: "Murf Falcon · En direct", demoBanner: "Mode demo actif - regardez simplement", switchThemeTo: "Basculer vers" },
    hero: { eyebrow: "INTERACTION VOCALE", title1: "Naviguez sur le web avec votre", titleAccent: "voix", subtitle: "SpeakSite transforme un site de demonstration en experience vocale avec analyse des commandes en temps reel et confirmations parlees.", trySaying: "ESSAYEZ DE DIRE", cmd1: '"aller a la page inscription"', cmd2: '"remplir email avec me@gmail.com"', cmd3: '"soumettre le formulaire"' },
    nav: { home: "Accueil", signup: "Inscription", contact: "Contact" },
    homePage: { tag: "PLATEFORME ENTREPRISE", title: "Travaillez plus intelligemment.", subtitle: "Creez une experience SaaS soignee avec des flux de travail vocaux.", ctaPrimary: "Commencer gratuitement ->", ctaPrimaryLoading: "Ouverture...", ctaSecondary: "Voir la demo", ctaSecondaryRunning: "Demo en cours...", demoWarmup: "Le mode demo se prepare encore. Reessayez dans un instant.", stat1Value: "48K+", stat1Label: "Equipes actives", stat2Value: "99.9%", stat2Label: "SLA disponibilite", stat3Value: "4.9★", stat3Label: "Note utilisateur", feature1Title: "Rapide par defaut", feature1Desc: "Temps de reponse inferieurs a 100 ms avec une infrastructure edge.", feature2Title: "Securite entreprise", feature2Desc: "Certifie SOC 2 Type II avec chiffrement de bout en bout.", feature3Title: "Analytique en temps reel", feature3Desc: "Tableaux de bord en direct avec KPI personnalises et export.", feature4Title: "Collaboration d'equipe", feature4Desc: "Commentaires, mentions et espaces partages integres." },
    signupPage: { tag: "CREER UN COMPTE", title: "Rejoignez des milliers d'equipes", subtitle: "Configurez votre compte gratuit en moins de 2 minutes.", labelFirstName: "Prenom", labelLastName: "Nom", labelEmail: "Adresse e-mail", labelPassword: "Mot de passe", placeholderFirstName: "Pierre", placeholderLastName: "Martin", placeholderEmail: "pierre@entreprise.com", placeholderPassword: "Min. 8 caracteres", voiceBadge: "voix", hint: 'Dites "soumettre le formulaire" ou cliquez ->', submitBtn: "Creer un compte", successMsg: "Compte cree avec succes. Bienvenue.", successIcon: "OK", subtitleAlt: "Configurez votre espace de travail en quelques minutes et gerez le formulaire par voix ou saisie manuelle." },
    contactPage: { tag: "CONTACTEZ-NOUS", title: "Nous aimerions avoir de vos nouvelles", subtitle: "Envoyez-nous un message et notre equipe repondra sous un jour ouvrable.", labelName: "Votre nom", labelEmail: "E-mail", labelMessage: "Message", placeholderName: "Nom complet", placeholderEmail: "vous@entreprise.com", placeholderMsg: "Dites-nous comment nous pouvons vous aider...", voiceBadge: "voix", hint: 'Dites "soumettre le formulaire" ou cliquez ->', submitBtn: "Envoyer le message", successMsg: "Message envoye. Nous vous contacterons sous 24 heures.", successIcon: "OK" },
    voicePanel: { title: "CONTROLE VOCAL", transcript: "TRANSCRIPTION", actionLog: "JOURNAL D'ACTIONS", response: "REPONSE", waiting: "En attente d'entree vocale...", clickToStart: "Cliquez pour commencer", listening: "Ecoute... parlez maintenant", processing: "Traitement de la commande...", speaking: "Lecture de la reponse...", noCommands: "Aucune commande pour l'instant", tryChips: "Essayez les puces ci-dessous", chip1: "page inscription", chip2: "page contact", chip3: "remplir nom", chip4: "soumettre", idlePrompt: "Cliquez sur le micro et dites une commande", repeatReady: "Je suis pret pour votre prochaine commande.", notCaught: "Je n'ai pas compris. Reessayez.", unsupported: "Votre navigateur ne prend pas en charge l'entree vocale. Essayez Chrome ou Edge.", demoRunning: "Demo en cours...", noSpeech: "Aucune voix detectee.", noMatch: "Je n'ai pas pu faire correspondre cela a une commande." },
    status: { idle: "Pret", listening: "Ecoute...", processing: "Traitement...", speaking: "Parole..." },
    languageSelector: { chooseLanguage: "Choisir la langue", female: "Feminin", male: "Masculin" },
    onboarding: { step1Title: "Bienvenue sur SpeakSite", step1Sub: "Le web, navigue entierement par la voix.", poweredBy: "PROPULSE PAR MURF FALCON AI", step2Title: "Voici ce que vous pouvez dire", card1Label: "NAVIGUER", card1Cmd: '"aller a la page inscription"', card2Label: "REMPLIR FORMULAIRES", card2Cmd: '"remplir email avec vous@mail.com"', card3Label: "SOUMETTRE", card3Cmd: '"soumettre le formulaire"', step3Title: "Choisissez votre langue", step3Sub: "SpeakSite parle votre langue, avec Murf Falcon.", startBtn: "Commencer a utiliser SpeakSite", skipLink: "Passer l'introduction" },
    helpModal: { title: "Commandes vocales", subtitle: "Dites l'une de ces phrases pour controler SpeakSite", navSection: "NAVIGATION", formSection: "FORMULAIRES", langSection: "LANGUE", demoSection: "DEMO", themeSection: "THEME", cmd_home: "aller a la page d'accueil", cmd_signup: "aller a la page inscription", cmd_contact: "ouvrir la page contact", cmd_fillName: "remplir nom avec [valeur]", cmd_fillEmail: "remplir email avec [valeur]", cmd_fillMsg: "remplir message avec [valeur]", cmd_submit: "soumettre le formulaire", cmd_hindi: "passer a l'hindi", cmd_english: "passer a l'anglais", cmd_demo: "demarrer la demo", cmd_stopDemo: "arreter la demo", cmd_help: "aide", cmd_light: "passer en mode clair", cmd_dark: "passer en mode sombre", desc_home: "Ouvre l'accueil", desc_signup: "Ouvre l'inscription", desc_contact: "Ouvre le contact", desc_fillName: "Remplit le champ nom", desc_fillEmail: "Remplit le champ e-mail", desc_fillMsg: "Remplit le champ message", desc_submit: "Soumet le formulaire actuel", desc_hindi: "Passe en hindi", desc_english: "Passe en anglais", desc_demo: "Lance la demo guidee", desc_stopDemo: "Arrete la demo", desc_help: "Affiche ce panneau", desc_light: "Passe au theme clair", desc_dark: "Passe au theme sombre", closeBtn: "x" },
    guidedDemo: { runBtn: "Lancer la demo", runIcon: "RUN", demoMode: "MODE DEMO", step: "Etape", stepOf: "sur", skipStep: "Passer l'etape", stopDemo: "Arreter la demo", running: "Demo en cours...", label1: "Introduction", label2: "Navigation vers Inscription", label3: "Remplissage du nom", label4: "Remplissage de l'e-mail", label5: "Soumission du formulaire", label6: "Demo terminee" },
    theme: { dark: "Sombre", light: "Clair" },
    logs: { navigatedHome: "Navigue vers Accueil", navigatedSignup: "Navigue vers Inscription", navigatedContact: "Navigue vers Contact", filledField: "Rempli", submittedForm: "Soumis", submittedSuffix: "formulaire", repeatedResponse: "Derniere reponse repetee", langSwitched: "Langue changee en", helpOpened: "Panneau d'aide ouvert", helpClosed: "Panneau d'aide ferme", unrecognized: "Commande non reconnue", themeLight: "Theme -> mode clair", themeDark: "Theme -> mode sombre", demoStopped: "Demo arretee par l'utilisateur", demoStartedButton: "Demo lancee depuis Voir la demo", getStartedNav: "Navigation vers Inscription depuis Commencer" }
  }
};

export default translations;
export const useTranslation = (langCode) => translations[langCode] || translations["en-US"];
